### ISSUE TITLE
Captcha Solving Alternative to DBC

### ISSUE THREAD

**Issue by Sorasma** [serphacker/serposcope#58]
Deathbycaptcha have long periods when they are down, they have this problem for long time, that's why I don't use them for long time now. They say that captcha solving does work even if main dashboard/login is down but we can't confirm that, and main problem is when you want to add founds to the account. For example I tried last 2 days to add founds but they always go down and I can't add any $ to the account. This is old problem with them, they are cheapes service and everybody use them but quality of service is very low, even for captcha solving.

We need a better Captcha solving service, one that is reliable. We don't use 1000's of captchas per day so a premium captcha service is better for our case. 

Because we don't consume so many captchas compared with a backlink tool, we need a captcha solver service that is:
1) fast.
2) has 100% recognition from first try if possible.

Here are my proposals, and I'm in now way affiliate with any of them, I just offer my user experience, that all:

1. Antigate (Anti-captcha.com)
I use them for long time and I don't have any problem with them, and service is good and cheap too, starting from 0.7USD per 1000 images.

Also they have great API integration that realy works and can be integratead very easy.
They also have have advanced captcha recognition setings, like "maximum bid" where you can setup the maximum bid per 1000 images that you want to pay, and this option gives your captchas priority among other client captchas, so you somehow speed the captcha solving time.
Also you have "100% recognition" option where all captchas will be send to multiple workers simultaneously. Their inputs are compared against each other and an answer which is entered by at least two workers is presumed to be the correct one.

"maximum bid" and "100% recognition" are optional advanced settings, that can get your captcha costs to 2-4 USD per 1000 images, but if you want standard solving, similar or even better then DBC you pay around 0.7USD per 1000 images

API doc here https://anti-captcha.com/apidoc

2. DeCaptcher (de-captcher.com)
This one is a premium service, does cost around 2USD per 1000 images, but you got it, it's premium service. Sure, for backlinks generation where you have lots of captchas to solve, this service may be expensive but for what we need this is fast and very good in recognition.

Api integration can be found inside each user account

**Comment by serphacker** [comment]
Hi, I agree, there is problem with deathbycaptcha now and because of this some user have trouble to use serposcope.  

I don't see any problem in adding 2 or 3 other alternatives. And I totally agree with you regarding we need premium service instead of cheap service. 

I know decaptcher and they are reliable, plus I already have implemented their API in java so it will be very quick to add it to serposcope. I'll check for other provider.

**Comment by serphacker** [comment]
added 2 more captcha provider deathbycaptcha and anti-captcha/antigate. Should be enough for now.

**Comment by Sorasma** [comment]
Dump question maybe, but I can't find the answer. How can we add this changes into our install? I've read the upgrade instructions, but there isn't a new version, just the serpscope_2.0.0.deb install.

**Comment by serphacker** [comment]
There is no dumb question :)

On github is hosted the source code of serposcope, which contains the last feature of serposcope most of the time. However, I don't build a new release (= .exe, .deb etc.) each time I add a new feature or edit the source code. Otherwise, sometimes you'll have severals release a day.

After a certain point, I build the new release which contains all the new stuff. You'll be notified via serposcope or follow https://twitter.com/serphacker_en on twitter. But I plan to ship the next release before the end of week.

**Comment by articlefr** [comment]
Here are a few more good alternatives to consider for automated captcha solving service.

1. https://www.captchasolutions.com/
2. http://www.solvecaptchas.com
